//go:build windows && amd64

package preset_api

import "sync"

// SupportedABIVersion is the only preset_rs C ABI accepted by this binding.
const SupportedABIVersion uint32 = 6

// handleState serializes close against calls using the same native handle.
// Wrappers are intentionally cheap to copy: every copy shares this state.
type handleState struct {
	sync.RWMutex
	value uintptr
}

type PresetDevice struct{ state *handleState }
type PresetCanUdsClient struct{ state *handleState }
type PresetLinUdsClient struct{ state *handleState }

func newHandle(value uintptr) *handleState {
	if value == 0 {
		return nil
	}
	return &handleState{value: value}
}

func withHandle(state *handleState, call func(uintptr) int32) int32 {
	if state == nil {
		return call(0)
	}
	state.RLock()
	defer state.RUnlock()
	return call(state.value)
}

func closeHandle(state *handleState, symbol string) int32 {
	if state == nil {
		return PRESET_OK
	}
	state.Lock()
	defer state.Unlock()
	value := state.value
	if value == 0 {
		return PRESET_OK
	}
	status := invokeStatus(symbol, pointer(&value))
	// The C contract owns the pointer update. Device close, for example, may
	// consume the handle while returning a non-zero backend shutdown status.
	state.value = value
	return status
}

func (device PresetDevice) IsClosed() bool       { return handleClosed(device.state) }
func (client PresetCanUdsClient) IsClosed() bool { return handleClosed(client.state) }
func (client PresetLinUdsClient) IsClosed() bool { return handleClosed(client.state) }

func handleClosed(state *handleState) bool {
	if state == nil {
		return true
	}
	state.RLock()
	defer state.RUnlock()
	return state.value == 0
}

const (
	PRESET_OK int32 = -iota
	PRESET_ERR_NULL_PTR
	PRESET_ERR_BUFFER_TOO_SMALL
	PRESET_ERR_NOT_INIT
	PRESET_ERR_TIMEOUT
	PRESET_ERR_UDS_NEGATIVE
	PRESET_ERR_TRANSPORT
	PRESET_ERR_UNSUPPORTED
	PRESET_ERR_INVALID_ARG
	PRESET_ERR_BUSY
	PRESET_ERR_ISOTP
	PRESET_ERR_PANIC
)

const (
	PRESET_CAP_CLASSIC_CAN uint64 = 1 << iota
	PRESET_CAP_CAN_FD
	PRESET_CAP_FUNCTIONAL
	PRESET_CAP_RAW_CAN
	PRESET_CAP_STANDARD_ID_ONLY
	PRESET_CAP_RUNTIME_FLOW_CONTROL
	PRESET_CAP_TOOMOSS_SHARED_DEVICE
	PRESET_CAP_TOOMOSS_LIN
	PRESET_CAP_TOOMOSS
	PRESET_CAP_TSMASTER
	PRESET_CAP_PCAN
	PRESET_CAP_VECTOR
	PRESET_CAP_TOOMOSS_ELINS
	PRESET_CAP_LIN_UDS
	PRESET_CAP_FILE_LOGGING
	PRESET_CAP_CAN_CHANNEL_SELECT
	PRESET_CAP_BUS_LOAD
	PRESET_CAP_RAW_CAN_METADATA
	PRESET_CAP_RUNTIME_BRS
	PRESET_CAP_EXPLICIT_FD_TIMING
	PRESET_CAP_AUTO_DRIVER
	PRESET_CAP_PCAN_LIN
	PRESET_CAP_TSMASTER_LIN
	PRESET_CAP_VECTOR_LIN
	PRESET_CAP_RAW_CAN_TIMESTAMP
)

const (
	PRESET_CAN_DIRECTION_TX = iota
	PRESET_CAN_DIRECTION_RX
)

const (
	PRESET_CAN_BACKEND_NONE = iota
	PRESET_CAN_BACKEND_TOOMOSS
	PRESET_CAN_BACKEND_TSMASTER
	PRESET_CAN_BACKEND_PCAN
	PRESET_CAN_BACKEND_VECTOR
)

const (
	PRESET_LOG_FILTER_OFF = iota
	PRESET_LOG_FILTER_LIST
)

const (
	PRESET_TOOMOSS_CHANNEL_1 byte = 1 << iota
	PRESET_TOOMOSS_CHANNEL_2
	PRESET_TOOMOSS_CHANNEL_3
	PRESET_TOOMOSS_CHANNEL_4
)

const (
	PRESET_TOOMOSS_LIN_POWER_0V = iota
	PRESET_TOOMOSS_LIN_POWER_12V
	PRESET_TOOMOSS_LIN_POWER_5V
)

const (
	PRESET_TOOMOSS_ELINS_VER_IND83080 = iota
	PRESET_TOOMOSS_ELINS_VER_IND83220
	PRESET_TOOMOSS_ELINS_VER_IND83010
)

const (
	PRESET_LIN_PROTOCOL_13 = iota
	PRESET_LIN_PROTOCOL_20
	PRESET_LIN_PROTOCOL_21
)

const (
	PRESET_LIN_FUNCTIONAL_NAD = 0x7e
	PRESET_LIN_BROADCAST_NAD  = 0x7f
)

const (
	PRESET_VECTOR_HWTYPE_ANY                    = -1
	PRESET_VECTOR_HWTYPE_NONE                   = 0
	PRESET_VECTOR_HWTYPE_VIRTUAL                = 1
	PRESET_VECTOR_HWTYPE_CANCARDX               = 2
	PRESET_VECTOR_HWTYPE_CANAC2PCI              = 6
	PRESET_VECTOR_HWTYPE_CANCARDY               = 12
	PRESET_VECTOR_HWTYPE_CANCARDXL              = 15
	PRESET_VECTOR_HWTYPE_CANCASEXL              = 21
	PRESET_VECTOR_HWTYPE_CANCASEXL_LOG_OBSOLETE = 23
	PRESET_VECTOR_HWTYPE_CANBOARDXL             = 25
	PRESET_VECTOR_HWTYPE_CANBOARDXL_PXI         = 27
	PRESET_VECTOR_HWTYPE_VN2600                 = 29
	PRESET_VECTOR_HWTYPE_VN2610                 = 29
	PRESET_VECTOR_HWTYPE_VN3300                 = 37
	PRESET_VECTOR_HWTYPE_VN3600                 = 39
	PRESET_VECTOR_HWTYPE_VN7600                 = 41
	PRESET_VECTOR_HWTYPE_CANCARDXLE             = 43
	PRESET_VECTOR_HWTYPE_VN8900                 = 45
	PRESET_VECTOR_HWTYPE_VN8950                 = 47
	PRESET_VECTOR_HWTYPE_VN2640                 = 53
	PRESET_VECTOR_HWTYPE_VN1610                 = 55
	PRESET_VECTOR_HWTYPE_VN1630                 = 57
	PRESET_VECTOR_HWTYPE_VN1640                 = 59
	PRESET_VECTOR_HWTYPE_VN8970                 = 61
	PRESET_VECTOR_HWTYPE_VN1611                 = 63
	PRESET_VECTOR_HWTYPE_VN5240                 = 64
	PRESET_VECTOR_HWTYPE_VN5610                 = 65
	PRESET_VECTOR_HWTYPE_VN5620                 = 66
	PRESET_VECTOR_HWTYPE_VN7570                 = 67
	PRESET_VECTOR_HWTYPE_VN5650                 = 68
	PRESET_VECTOR_HWTYPE_IPCLIENT               = 69
	PRESET_VECTOR_HWTYPE_IPSERVER               = 71
	PRESET_VECTOR_HWTYPE_VX1121                 = 73
	PRESET_VECTOR_HWTYPE_VX1131                 = 75
	PRESET_VECTOR_HWTYPE_VT6204                 = 77
	PRESET_VECTOR_HWTYPE_VN1630_LOG             = 79
	PRESET_VECTOR_HWTYPE_VN7610                 = 81
	PRESET_VECTOR_HWTYPE_VN7572                 = 83
	PRESET_VECTOR_HWTYPE_VN8972                 = 85
	PRESET_VECTOR_HWTYPE_VN0601                 = 87
	PRESET_VECTOR_HWTYPE_VN5640                 = 89
	PRESET_VECTOR_HWTYPE_VX0312                 = 91
	PRESET_VECTOR_HWTYPE_VH6501                 = 94
	PRESET_VECTOR_HWTYPE_VN8800                 = 95
	PRESET_VECTOR_HWTYPE_IPCL8800               = 96
	PRESET_VECTOR_HWTYPE_IPSRV8800              = 97
	PRESET_VECTOR_HWTYPE_CSMCAN                 = 98
	PRESET_VECTOR_HWTYPE_VN5610A                = 101
	PRESET_VECTOR_HWTYPE_VN7640                 = 102
	PRESET_VECTOR_HWTYPE_VX1135                 = 104
	PRESET_VECTOR_HWTYPE_VN4610                 = 105
	PRESET_VECTOR_HWTYPE_VT6306                 = 107
	PRESET_VECTOR_HWTYPE_VT6104A                = 108
	PRESET_VECTOR_HWTYPE_VN5430                 = 109
	PRESET_VECTOR_HWTYPE_VTSSERVICE             = 110
	PRESET_VECTOR_HWTYPE_VN1530                 = 112
	PRESET_VECTOR_HWTYPE_VN1531                 = 113
	PRESET_VECTOR_HWTYPE_VX1161A                = 114
	PRESET_VECTOR_HWTYPE_VX1161B                = 115
)
const (
	PRESET_TSMASTER_TSCAN_PRO = iota + 1
	PRESET_TSMASTER_TSCAN_LITE1
	PRESET_TSMASTER_TC1001
	PRESET_TSMASTER_TL1001
	PRESET_TSMASTER_TC1011
	PRESET_TSMASTER_TM5011
	PRESET_TSMASTER_TC1002
	PRESET_TSMASTER_TC1014
	PRESET_TSMASTER_TSCANFD2517
	PRESET_TSMASTER_TC1026
	PRESET_TSMASTER_TC1016
	PRESET_TSMASTER_TC1012
	PRESET_TSMASTER_TC1013
	PRESET_TSMASTER_TLOG1002
	PRESET_TSMASTER_TC1034
	PRESET_TSMASTER_TC1018
	PRESET_TSMASTER_GW2116
	PRESET_TSMASTER_TC2115
	PRESET_TSMASTER_MP1013
	PRESET_TSMASTER_TC1113
	PRESET_TSMASTER_TC1114
	PRESET_TSMASTER_TP1013
	PRESET_TSMASTER_TC1017
	PRESET_TSMASTER_TP1018
	PRESET_TSMASTER_TF10XX
	PRESET_TSMASTER_TL1004_FD_4_LIN_2
	PRESET_TSMASTER_TE1051
	PRESET_TSMASTER_TP1051
	PRESET_TSMASTER_TP1034
	PRESET_TSMASTER_TTS9015
	PRESET_TSMASTER_TP1026
	PRESET_TSMASTER_TTS1026
	PRESET_TSMASTER_TTS1034
	PRESET_TSMASTER_TTS1018
	PRESET_TSMASTER_TL1011
	PRESET_TSMASTER_TTS1015_LIAUTO
	PRESET_TSMASTER_TTS1013_LIAUTO
	PRESET_TSMASTER_TTS1016PRO
	PRESET_TSMASTER_TC1054PRO
	PRESET_TSMASTER_TC1054
	PRESET_TSMASTER_TLOG1038
	PRESET_TSMASTER_TO1013
	PRESET_TSMASTER_TC1034PRO
	PRESET_TSMASTER_TC1018PRO
	PRESET_TSMASTER_TC1038PRO
	PRESET_TSMASTER_TC1014PRO
	PRESET_TSMASTER_TC1034PROPLUS
	PRESET_TSMASTER_TA1038
	PRESET_TSMASTER_TC1055PRO
	PRESET_TSMASTER_TC1056PRO
	PRESET_TSMASTER_TC1057PRO
	PRESET_TSMASTER_TC4016
	PRESET_TSMASTER_GW2208
	PRESET_TSMASTER_TLOG1039
	PRESET_TSMASTER_GW1040
	PRESET_TSMASTER_TC3014
	PRESET_TSMASTER_TP1014
	PRESET_TSMASTER_TA825_4
	PRESET_TSMASTER_TC1013HV
	PRESET_TSMASTER_TC1052
	PRESET_TSMASTER_TTS1017PRO
	PRESET_TSMASTER_TLOG1057
	PRESET_TSMASTER_TC1017PRO
	PRESET_TSMASTER_GW2202
	PRESET_TSMASTER_GW2204
	PRESET_TSMASTER_GW2212
	PRESET_TSMASTER_TA821
	PRESET_TSMASTER_TX1000
	PRESET_TSMASTER_TC1055PROPLUS
	PRESET_TSMASTER_TC1043
)
